thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "1.13 Invalid reference \"fart\""', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
